services:
  glam-client:
    container_name: glam_client
    image: ${DOCKER_USERNAME}/glam-client:latest
    ports:
      - 4000:3000
    environment:
      NEXT_PUBLIC_AUTH_HOST: ${NEXT_PUBLIC_AUTH_HOST}
      NEXT_PUBLIC_BUSINESS_HOST: ${NEXT_PUBLIC_BUSINESS_HOST}
      NEXT_PUBLIC_SYSTEM_HOST: ${NEXT_PUBLIC_SYSTEM_HOST}
      NEXT_PUBLIC_USER_HOST: ${NEXT_PUBLIC_USER_HOST}
      NEXT_PUBLIC_WEBSOCKET_HOST: ${NEXT_PUBLIC_WEBSOCKET_HOST}
      NEXT_PUBLIC_WORKER_HOST: ${NEXT_PUBLIC_WORKER_HOST}
    networks:
      - glam-networks
    restart: always

networks:
  glam-networks:
    name: glam_networks
    external: true