services:
  glam-client:
    container_name: glam_client
    image: ${DOCKER_USERNAME}/glam-client:latest
    ports:
      - 4000:3000
    networks:
      - glam-networks

networks:
  glam-networks:
    name: glam_networks
    external: true