on: 
    push:
        branches: 
            - main

jobs:
    build-image:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Develop
              uses: actions/checkout@v3

            - name: DockerHub Login
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Build Image And Push
              run: docker compose build glam-client && docker compose push

    client-deploy:
        runs-on: arisa-server
        needs: build-image
        env: 
            DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        steps:
          - name: Checkout Develop
            uses: actions/checkout@v3
          - name: DockerHub Login
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
              
          - name: Clean Container, Image And Prepare For Deploy
            run: docker compose -f docker-compose.prod.yaml -p glam-client down --rmi all -v
          - name: Deploy Client
            run: docker compose -f docker-compose.prod.yaml -p glam-client up -d